"""create financial metrics

Revision ID: 00387967aff6
Revises: 
Create Date: 2026-08-25 17:34:44.309984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00387967aff6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.String(length=255), nullable=True),
    sa.Column('net_income', sa.String(length=255), nullable=True),
    sa.Column('operating_income', sa.String(length=255), nullable=True),
    sa.Column('operating_cash_flow', sa.String(length=255), nullable=True),
    sa.Column('total_assets', sa.String(length=255), nullable=True),
    sa.Column('total_liabilities', sa.String(length=255), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('growth_drivers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'fiscal_year', name='uq_company_fiscal_year')
    )
    op.create_index(op.f('ix_financial_metrics_company'), 'financial_metrics', ['company'], unique=False)
    op.create_index(op.f('ix_financial_metrics_document_id'), 'financial_metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_fiscal_year'), 'financial_metrics', ['fiscal_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_metrics_fiscal_year'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_document_id'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_company'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    # ### end Alembic commands ###
